//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetHimCook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comments()
        {
            this.Comments1 = new HashSet<Comments>();
            this.Likes = new HashSet<Likes>();
            this.Reports = new HashSet<Reports>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Text { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BlogPosts BlogPosts { get; set; }
        public virtual Collections Collections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual Comments Comments2 { get; set; }
        public virtual Recipes Recipes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Likes> Likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
