//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetHimCook
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngRec
    {
        public int ID { get; set; }
        public int RecipeID { get; set; }
        public int IngridientID { get; set; }
    
        public virtual Ingridients Ingridients { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
