//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetHimCook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LetHimCookEntities : DbContext
    {
        public LetHimCookEntities()
            : base("name=LetHimCookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogPosts> BlogPosts { get; set; }
        public virtual DbSet<CollectionRecipe> CollectionRecipe { get; set; }
        public virtual DbSet<Collections> Collections { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Difficulties> Difficulties { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<Follows> Follows { get; set; }
        public virtual DbSet<IngRec> IngRec { get; set; }
        public virtual DbSet<Ingridients> Ingridients { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<RecipeTags> RecipeTags { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
