//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetHimCook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> PostID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual BlogPosts BlogPosts { get; set; }
        public virtual Collections Collections { get; set; }
        public virtual Comments Comments { get; set; }
        public virtual Recipes Recipes { get; set; }
        public virtual Users Users { get; set; }
    }
}
