//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetHimCook
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeTags
    {
        public int ID { get; set; }
        public int TagID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public Nullable<int> BlogID { get; set; }
        public Nullable<int> TypeID { get; set; }
    
        public virtual BlogPosts BlogPosts { get; set; }
        public virtual Collections Collections { get; set; }
        public virtual Recipes Recipes { get; set; }
        public virtual Tags Tags { get; set; }
        public virtual Types Types { get; set; }
    }
}
